const teamIndia = [
  {
    name: "Rohit Sharma",
    spouse: "Ritika Sajdeh",
    jersey: 45,
    born: "Nagpur",
    role: "Batsman",
    image: "https://upload.wikimedia.org/wikipedia/commons/1/1e/Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Shri_Rohit_Gurunath_Sharma_%28Cropped%29.jpg",
    country: "India",
  },
  {
    name: "Shubman Gill",
    spouse: "",
    jersey: 77,
    born: "Fazilka",
    role: "Batsman",
    image: "https://upload.wikimedia.org/wikipedia/commons/3/34/Shubman_Gill_2023_%28cropped%29.jpg",
    country: "India",
  },
  {
    name: "Yashasvi Jaiswal",
    spouse: "",
    jersey: 64,
    born: "Suriyawan",
    role: "Batsman",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Yashasvi_Jaiswal_in_PMO_New_Delhi.jpg/330px-Yashasvi_Jaiswal_in_PMO_New_Delhi.jpg",
    country: "India",
  },
  {
    name: "Ruturaj Gaikwad",
    spouse: "Utkarsha Pawar",
    jersey: 31,
    born: "Pune",
    role: "Batsman",
    image: "https://www.jansatta.com/wp-content/uploads/2024/05/rituraj-gaikwad.jpg?w=489",
    country: "India",
  },
  {
    name: "Virat Kohli",
    spouse: "Anushka Sharma",
    jersey: 18,
    born: "Delhi",
    role: "Batsman",
    image: "https://static.toiimg.com/thumb/msid-111528868,width-1280,height-720,resizemode-4/111528868.jpg",
    country: "India",
  },
  {
    name: "Shreyas Iyer",
    spouse: "",
    jersey: 96,
    born: "Chembur, Mumbai",
    role: "Batsman",
    image: "https://scontent.fknu1-6.fna.fbcdn.net/v/t1.6435-1/71171622_2171678399602949_2279615842960277504_n.jpg?stp=dst-jpg_s200x200&_nc_cat=103&ccb=1-7&_nc_sid=f4b9fd&_nc_ohc=wWKaSqGGuF0Q7kNvgHx15ad&_nc_zt=24&_nc_ht=scontent.fknu1-6.fna&_nc_gid=AzNGjWugxEvk-rMacy7Pw48&oh=00_AYDpsFlhp0uBsneJ27RnN68FiP6fBe3A197ZRJZUg4S4ig&oe=67593942",
    country: "India",
  },
  {
    name: "Suryakumar Yadav",
    spouse: "Devisha Shetty",
    jersey: 63,
    born: "Mumbai",
    role: "Batsman",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Suryakumar_Yadav_in_PMO_New_Delhi.jpg/330px-Suryakumar_Yadav_in_PMO_New_Delhi.jpg",
    country: "India",
  },
  {
    name: "Tilak Varma",
    spouse: "",
    jersey: 72,
    born: "Hyderabad",
    role: "Batsman",
    image: "https://i.pinimg.com/736x/a3/b6/53/a3b6537ea149542073f376dfd0ff52d3.jpg",
    country: "India",
  },
  {
    name: "Rishabh Pant",
    spouse: "",
    jersey: 17,
    born: "Roorkee",
    role: "WK-Batsman",
    image: "https://images.news18.com/ibnlive/uploads/2024/06/rishabh-pant-looking-forward-to-the-india-vs-pakistan-clash-2024-06-b2d7c5c5fd82f38c33a896325cdb599c.jpg?impolicy=website&width=360&height=270",
    country: "India",
  },
  {
    name: "KL Rahul",
    spouse: "Athiya Shetty",
    jersey: 1,
    born: "Bengaluru",
    role: "WK-Batsman",
    image: "https://api.bdcrictime.com/Profile/kl-rahul-14_10_2023.jpg",
    country: "India",
  },
  {
    name: "Ishan Kishan",
    spouse: "",
    jersey: 32,
    born: "Patna",
    role: "WK-Batsman",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Ishan_Kishan.jpg/330px-Ishan_Kishan.jpg",
    country: "India",
  },
  {
    name: "Sanju Samson",
    spouse: "Charulatha Samson",
    jersey: 9,
    born: "Pulluvila",
    role: "WK-Batsman",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Sanju_Samson_in_PMO_New_Delhi.jpg/330px-Sanju_Samson_in_PMO_New_Delhi.jpg",
    country: "India",
  },
  {
    name: "Rinku Singh",
    spouse: "",
    jersey: 35,
    born: "Aligarh",
    role: "Batsman",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/RinkuSingh_Ireland_vs_India.jpg/330px-RinkuSingh_Ireland_vs_India.jpg",
    country: "India",
  },
  {
    name: "Hardik Pandya",
    spouse: "Nataša Stanković",
    jersey: 33,
    born: "Choryasi Assembly constituency",
    role: "Batting Allrounder",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Hardik_Pandya_in_PMO_New_Delhi.jpg/330px-Hardik_Pandya_in_PMO_New_Delhi.jpg",
    country: "India",
  },
  {
    name: "Shivam Dube",
    spouse: "Anjum Khan",
    jersey: 25,
    born: "Mumbai",
    role: "Batting Allrounde",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Shivam_Dube_in_PMO_New_Delhi.jpg/330px-Shivam_Dube_in_PMO_New_Delhi.jpg",
    country: "India",
  },
  {
    name: "Axar Patel",
    spouse: "Meha Patel",
    jersey: 20,
    born: "Anand",
    role: "Bowling Allrounder",
    image: "https://media.sportstiger.com/players/AxarPatel01-08-2021-10-14-40.png",
    country: "India",
  },
  {
    name: "Kuldeep Yadav",
    spouse: "",
    jersey: 23,
    born: "Kanpur",
    role: "Bowler",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Kuldeep_Yadav_in_PMO_New_Delhi.jpg/330px-Kuldeep_Yadav_in_PMO_New_Delhi.jpg",
    country: "India",
  },
  {
    name: "Ravi Bishnoi",
    spouse: "",
    jersey: 56,
    born: "Jodhpur",
    role: "Bowler",
    image: "https://scontent.flko10-1.fna.fbcdn.net/v/t39.30808-6/409994411_892166255812032_9105675395251982289_n.jpg?stp=dst-jpg_s600x600&_nc_cat=102&ccb=1-7&_nc_sid=833d8c&_nc_ohc=ONXs0i3i5hwQ7kNvgGnPx0f&_nc_zt=23&_nc_ht=scontent.flko10-1.fna&_nc_gid=AWV55eWMFyFkTEqAwTmwdYq&oh=00_AYC2X5P7pzN6vmQ7S2o_Oku9v3zIRyljRYy7oECUbHAIKQ&oe=673823FF",
    country: "India",
  },
  {
    name: "Mohammed Shami",
    spouse: "Hasin Jahan",
    jersey: 11,
    born: "Sahaspur Alinagar",
    role: "Bowler",
    image: "https://myfinal11.b-cdn.net/wp-content/uploads/2024/10/Mohammed-Shami-Reacts-to-Missing-Out-on-the-Squad.webp",
    country: "India",
  },
  {
    name: "Arshdeep Singh",
    spouse: "",
    jersey: 2,
    born: "Guna",
    role: "Bowler",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Arshdeep_Singh_Family_%28Cropped%29.jpg/330px-Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Arshdeep_Singh_Family_%28Cropped%29.jpg",
    country: "India",
  },
  {
    name: "Jasprit Bumrah",
    spouse: "Sanjana Ganesan",
    jersey: 93,
    born: "Ahmedabad",
    role: "Bowler",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/02/Jasprit_Bumrah_in_PMO_New_Delhi.jpg",
    country: "India",
  },
  {
    name: "Mohammed Siraj",
    spouse: "",
    jersey: 73,
    born: "Hyderabad",
    role: "Bowler",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Mohammad_Siraj_%28cropped%29.jpg/330px-Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Mohammad_Siraj_%28cropped%29.jpg",
    country: "India",
  },
  {
    name: "Mayank Yadav",
    spouse: "",
    jersey: 44,
    born: "Delhi",
    role: "Bowler",
    image: "https://scontent.flko9-1.fna.fbcdn.net/v/t39.30808-6/461480115_1320363629361592_8584126835676661699_n.jpg?stp=dst-jpg_s640x640&_nc_cat=102&ccb=1-7&_nc_sid=833d8c&_nc_ohc=ErfvwDR9WAoQ7kNvgG3nav4&_nc_zt=23&_nc_ht=scontent.flko9-1.fna&_nc_gid=AesHGzycZ8YnoVKEFAnRM8F&oh=00_AYCJHH5b42vEp1o_Q0UIZ06XxfMYuwVtOyuHR_2E_3-1HQ&oe=6737A9DF",
    country: "India",
  },
];

module.exports = { data: teamIndia };
